# cloudbuild-sub.yaml

logsBucket: 'gs://wys-test' # IMPORTANT: Replace with your actual bucket name for logs.

steps:
  # 步骤 1: 克隆 Git 仓库
  - name: 'gcr.io/cloud-builders/git'
    args: ['clone', 'https://github.com/wengyisheng/nginx-test', '.']
    id: 'clone-repo'

  # 步骤 2: 获取 Git Tag 作为镜像版本
  # 将GIT_TAG直接写入一个文件，后续步骤通过source来获取
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        GIT_TAG=$(git describe --tags --abbrev=0)
        if [ -z "$GIT_TAG" ]; then
          echo "Error: No Git tag found. Please tag your repository."
          exit 1
        fi
        echo "export GIT_TAG=$GIT_TAG" > /workspace/env_vars.sh # 注意这里使用了 export
    id: 'get-git-tag'
    
  # 步骤 3: 构建 Docker 镜像
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash' # 使用 bash 作为入口点来执行 source 命令
    args:
      - '-c'
      - |
        source /workspace/env_vars.sh # 载入环境变量
        docker build -f Dockerfile -t us-east1-docker.pkg.dev/gcp-support-test-347006/wengyisheng/nginx-test:$GIT_TAG .
    id: 'build-docker-image'
    waitFor: ['get-git-tag'] # 确保在获取到tag后才构建

  # 步骤 4: 推送 Docker 镜像到 Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash' # 使用 bash 作为入口点来执行 source 命令
    args:
      - '-c'
      - |
        source /workspace/env_vars.sh # 载入环境变量
        docker push us-east1-docker.pkg.dev/gcp-support-test-347006/wengyisheng/nginx-test:$GIT_TAG
    id: 'push-to-artifact-registry'
    waitFor: ['build-docker-image'] # 确保在构建后才推送

  # 步骤 5: 在测试实例上运行 Docker 镜像进行测试
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        source /workspace/env_vars.sh # 载入环境变量
        
        INSTANCE_NAME="tp-link-dev-gpu-2"
        ZONE="us-east1-c"
        IMAGE_NAME="us-east1-docker.pkg.dev/gcp-support-test-347006/wengyisheng/nginx-test:$GIT_TAG"
        
        echo "Attempting to run Docker on $INSTANCE_NAME in $ZONE..."
        
        # 停止并删除可能存在的同名容器，避免端口冲突或旧镜像影响
        gcloud compute ssh ${INSTANCE_NAME} --zone=${ZONE} --command="docker stop nginx-test-container || true && docker rm nginx-test-container || true"
        
        # 运行新的Docker容器
        gcloud compute ssh ${INSTANCE_NAME} --zone=${ZONE} --command="docker run -d --name nginx-test-container -p 80:80 ${IMAGE_NAME}"
        
        # 简单验证容器是否运行，您可以根据需要添加更复杂的健康检查
        echo "Waiting for container to start..."
        sleep 10 # 给予容器启动时间
        CONTAINER_STATUS=$(gcloud compute ssh ${INSTANCE_NAME} --zone=${ZONE} --command="docker ps -f name=nginx-test-container --format '{{.Status}}'")
        echo "Container status: $CONTAINER_STATUS"
        
        if [[ "$CONTAINER_STATUS" != *"Up"* ]]; then
          echo "Error: Docker container 'nginx-test-container' did not start successfully."
          gcloud compute ssh ${INSTANCE_NAME} --zone=${ZONE} --command="docker logs nginx-test-container"
          exit 1
        else
          echo "Docker container 'nginx-test-container' is running successfully."
        fi
    id: 'docker-run-test'
    waitFor: ['push-to-artifact-registry'] # 确保在推送镜像成功后才进行测试
